# Generated by Django 4.1.4 on 2022-12-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastname',
            new_name='username',
        ),
    ]
