# Generated by Django 4.1.4 on 2022-12-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_firstname_members_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
